/* Assemble js/levels.js from tools/handmade.js + tools/generated.json, verifying every level
 * with the solver and deriving the time limit from the solution length.
 *   node tools/build-levels.js
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { solve, verify, lint } = require('./solve.js');
const HAND = require('./handmade.js');
const GEN = {};
const GEN_DIR = path.join(__dirname, 'gen_out');
for (const f of fs.existsSync(GEN_DIR) ? fs.readdirSync(GEN_DIR) : []) {
  if (f.endsWith('.json')) GEN[f.slice(0, -5)] = JSON.parse(fs.readFileSync(path.join(GEN_DIR, f), 'utf8'));
}

// [name, source, tip, hard]
const ORDER = [
  ['初次見面', 'hand:tutorial', 'drag'],
  ['讓個路', 'gen:l02', 'block'],
  ['小小塞車', 'gen:l03'],
  ['門的大小', 'gen:l04', 'width'],
  ['奇形怪狀', 'gen:l05', 'shapes'],
  ['擠一擠', 'gen:l06'],
  ['單向通行', 'gen:l07', 'dir'],
  ['橫衝直撞', 'gen:l08'],
  ['石頭路障', 'gen:l09', 'walls'],
  ['第一道考驗', 'gen:l10', null, true],
  ['冰封方塊', 'gen:l11', 'ice'],
  ['冰與箭頭', 'gen:l12'],
  ['鑰匙與鎖', 'gen:l13', 'lock'],
  ['冰封寶庫', 'gen:l14'],
  ['彩虹抽屜', 'hand:rainbowMini', 'rainbow', true],
  ['雙層外殼', 'gen:l16', 'layer'],
  ['層層剝開', 'gen:l17'],
  ['方塊製造機', 'gen:l18', 'gen'],
  ['雙機並行', 'gen:l19'],
  ['大挑戰', 'gen:l20', null, true],
  ['移動的門', 'gen:l21', 'move'],
  ['追著門跑', 'gen:l22'],
  ['藤蔓封門', 'gen:l23', 'ivy'],
  ['秘密花園', 'gen:l24'],
  ['混亂工廠', 'gen:l25', null, true],
  ['變色門', 'gen:l26', 'cycle'],
  ['霓虹工廠', 'gen:l27'],
  ['全員集合', 'gen:l28'],
  ['極限挑戰', 'gen:l29', null, true],
  ['彩虹終點', 'hand:rainbowBoss', null, true],
];

const round5 = v => Math.round(v / 5) * 5;
const partial = process.argv.includes('--partial'); // dev only: skip levels not generated yet
const levels = [];
let failed = 0;

ORDER.forEach(([name, src, tip, hard], idx) => {
  const [kind, id] = src.split(':');
  const def = kind === 'hand' ? HAND[id] : GEN[id] && GEN[id].def;
  if (!def) { console.log(idx + 1, name, 'MISSING', src); if (!partial) failed++; return; }
  const errs = lint(def);
  const res = solve(def, { bfsCap: 60000, bestCap: 1500000 });
  const v = res.ok ? verify(def, res.path) : 'unsolved';
  if (errs.length || v) { console.log(idx + 1, name, 'FAIL', errs, v); failed++; return; }
  const exits = res.actions - res.placements;
  const t = Math.min(300, Math.max(45, round5(25 + exits * 2.5 + res.placements * 7)));
  const lvl = { name, t };
  if (tip) lvl.tip = tip;
  if (hard) lvl.hard = 1;
  Object.assign(lvl, { map: def.map, key: def.key, doors: def.doors });
  if (def.gens && def.gens.length) lvl.gens = def.gens;
  lvl.par = res.placements; // solver's placement count (min when exact)
  levels.push(lvl);
  console.log(String(idx + 1).padStart(2), name.padEnd(6, '　'), 'place', (res.exact ? '' : '<=') + res.placements, 'acts', res.actions, 'time', t + 's');
});

if (failed) { console.log(failed, 'level(s) failed — levels.js not written'); process.exit(1); }

const body = levels.map(l => '  ' + JSON.stringify(l)).join(',\n');
const out = `/* Brick Escape — 30 levels. Generated by tools/build-levels.js (every level solver-verified). */
const LEVELS = [
${body}
];
if (typeof module !== 'undefined' && module.exports) module.exports = LEVELS;
`;
fs.writeFileSync(path.join(__dirname, '..', 'js', 'levels.js'), out);
console.log('wrote js/levels.js with', levels.length, 'levels');
